version: '3'

services:
  java_container:
    image: openjdk:17-oracle
    container_name: java_container
    networks:
      - my_network
    working_dir: /app
    command: ["java", "-Xmx100m", "-jar", "/app/your-java-app.jar"]
    ports:
      - "8080:8080"
    volumes:
      - ./dbtree-client-0.0.1-SNAPSHOT-plain.jar:/app/your-java-application.jar

  dbtree1:
    image: openjdk:17-oracle
    container_name: dbtree1
    networks:
      - my_network
    working_dir: /app
    command: ["java", "-Xmx100m", "-jar", "/app/dbtree-server-0.0.1-SNAPSHOT-plain.jar"]
    ports:
      - "3210:3210"
    volumes:
      - ./dbtree-server-0.0.1-SNAPSHOT-plain.jar:/app/dbtree-server-0.0.1-SNAPSHOT-plain.jar

  dbtree2:
    image: openjdk:17-oracle
    container_name: dbtree2
    networks:
      - my_network
    working_dir: /app
    command: ["java", "-Xmx100m", "-jar", "/app/dbtree-server-0.0.1-SNAPSHOT-plain.jar"]
    ports:
      - "3211:3210"
    volumes:
      - ./dbtree-server-0.0.1-SNAPSHOT-plain.jar:/app/dbtree-server-0.0.1-SNAPSHOT-plain.jar

  dbtree3:
    image: openjdk:17-oracle
    container_name: dbtree3
    networks:
      - my_network
    working_dir: /app
    command: ["java", "-Xmx100m", "-jar", "/app/dbtree-server-0.0.1-SNAPSHOT-plain.jar"]
    ports:
      - "3212:3210"
    volumes:
      - ./dbtree-server-0.0.1-SNAPSHOT-plain.jar:/app/dbtree-server-0.0.1-SNAPSHOT-plain.jar

  dbtree4:
    image: openjdk:17-oracle
    container_name: dbtree4
    networks:
      - my_network
    working_dir: /app
    command: ["java", "-Xmx100m", "-jar", "/app/dbtree-server-0.0.1-SNAPSHOT-plain.jar"]
    ports:
      - "3213:3210"
    volumes:
      - ./dbtree-server-0.0.1-SNAPSHOT-plain.jar:/app/dbtree-server-0.0.1-SNAPSHOT-plain.jar

networks:
  my_network:
    driver: bridge