server:
  port: 8080

integration:
  dbtree:
    db1:
      url: http://dbtree1:3333
    db2:
      url: http://dbtree2:3333
    db3:
      url: http://dbtree3:3333
    db4:
      url: http://dbtree4:3333